# Generated by Django 6.0.3 on 2026-03-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "todo", "verbose_name_plural": "todo 목록"},
        ),
    ]
