# Generated by Django 6.0.3 on 2026-03-23 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="todo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="todo.todo",
            ),
        ),
    ]
