# Generated by Django 6.0.3 on 2026-03-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0006_alter_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="todo/%Y/%m/%d"),
        ),
    ]
