# Generated by Django 6.0.3 on 2026-03-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0007_todo_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="todo/%Y/%m/%d/thumbnail"
            ),
        ),
    ]
